services:
  - type: web
    name: restaurant-rating-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: true 